name: Deploy Shopify Theme

on:
  push:
    branches:
      - main # Runs deployment when changes are pushed to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node dependencies
        run: npm install

      - name: Build theme
        run: npm run build
        # This creates dist/ at build time in the CI environment

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli

      - name: Deploy to Shopify
        run: shopify theme push --theme 176870162764 \
          --store ${{ secrets.SHOPIFY_STORE_URL }} \
          --password ${{ secrets.SHOPIFY_ACCESS_TOKEN }} \
          --path dist/
