name: Deploy Shopify Theme

on:
  push:
    branches:
      - main # Runs deployment when changes are pushed to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node dependencies
        run: npm install

      - name: Create assets directory
        run: mkdir -p assets

      - name: Build theme
        run: npm run build
        # This creates dist/ at build time in the CI environment

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli

      - name: Deploy to Shopify
        working-directory: dist
        env:
          SHOPIFY_FLAG_STORE: ${{ secrets.SHOPIFY_STORE_URL }}
          SHOPIFY_FLAG_PASSWORD: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
        run: shopify theme push --theme 176870162764
